//Code generated by game config export tool. DO NOT EDIT.

//AttributeEnum 道具属性枚举
enum AttributeEnum
{
	//AttributeHP 血量
	AttributeHP = 1,
	//AttributeMP 魔法值
	AttributeMP = 2,
	//AttributePATK 物理攻击
	AttributePATK = 3,
	//AttributeMATK 魔法攻击
	AttributeMATK = 4,
};
