//Code generated by game config export tool. DO NOT EDIT.
#pragma once
#include <Singleton.h>
#include <TableBase.h>

enum AttributeEnum;

//EquipAttStruct 装备属性结构体
struct EquipAttStruct
{
	//Index 属性类型
	AttributeEnum Index;
	//Value 属性值
	int32_t Value;

	void Parse(const JSONValue &v)
	{
		PARSE_FIELD(Index);
		PARSE_FIELD(Value);
	}

	void Relate()
	{
	}
};
