//Code generated by game config export tool. DO NOT EDIT.

//EquipPosEnum 装备部位枚举
enum EquipPosEnum
{
	//EquipPosCoat 衣服
	EquipPosCoat = 1,
	//EquipPosWeapon 武器
	EquipPosWeapon = 2,
	//EquipPosTrousers 裤子
	EquipPosTrousers = 3,
	//EquipPosHat 帽子
	EquipPosHat = 4,
	//EquipPosGloves 手套
	EquipPosGloves = 5,
	//EquipPosShoes 鞋子
	EquipPosShoes = 6,
	//EquipPosNecklace 项链
	EquipPosNecklace = 7,
	//EquipPosBelt 腰带
	EquipPosBelt = 8,
};
