//Code generated by game config export tool. DO NOT EDIT.

//ItemTypeEnum 道具类型
enum ItemTypeEnum
{
	//ItemTypeResource 资源
	ItemTypeResource = 1,
	//ItemTypeGift 礼包
	ItemTypeGift = 2,
	//ItemTypeMedicinal 药品
	ItemTypeMedicinal = 3,
	//ItemTypeMaterial 资源
	ItemTypeMaterial = 4,
	//ItemTypeEquip 装备
	ItemTypeEquip = 5,
};
