//Code generated by game config export tool. DO NOT EDIT.
#pragma once
#include <Singleton.h>
#include <TableBase.h>

class QuestStruct;
typedef const QuestStruct *QuestStructPtr;
#define QuestTable TableBase<QuestStruct>::GetInstance()

//QuestStruct 任务表
struct QuestStruct
{
	//ID ID
	uint32_t ID;
	//Name 任务名称
	std::string Name;
	//Reward 奖励道具
	std::vector<uint32_t> Reward;

	typedef uint32_t KEY_TYPE;
	KEY_TYPE GetKey() { return this->ID; }

	void Parse(const JSONValue &v)
	{
		PARSE_FIELD(ID);
		PARSE_FIELD(Name);
		PARSE_ARRAY(Reward, uint32_t);
	}

	void Relate()
	{
	}
};
