// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

// AttributeEnum 道具属性枚举
type AttributeEnum int

const (
	// AttributeHP 血量
	AttributeHP AttributeEnum = 1
	// AttributeMP 魔法值
	AttributeMP AttributeEnum = 2
	// AttributePATK 物理攻击
	AttributePATK AttributeEnum = 3
	// AttributeMATK 魔法攻击
	AttributeMATK AttributeEnum = 4
)