// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

// EquipPosEnum 装备部位枚举
type EquipPosEnum int

const (
	// EquipPosCoat 衣服
	EquipPosCoat EquipPosEnum = 1
	// EquipPosWeapon 武器
	EquipPosWeapon EquipPosEnum = 2
	// EquipPosTrousers 裤子
	EquipPosTrousers EquipPosEnum = 3
	// EquipPosHat 帽子
	EquipPosHat EquipPosEnum = 4
	// EquipPosGloves 手套
	EquipPosGloves EquipPosEnum = 5
	// EquipPosShoes 鞋子
	EquipPosShoes EquipPosEnum = 6
	// EquipPosNecklace 项链
	EquipPosNecklace EquipPosEnum = 7
	// EquipPosBelt 腰带
	EquipPosBelt EquipPosEnum = 8
)