// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

import (
	"encoding/json"
	"log"
)

// EquipAttStruct 装备属性结构体
type EquipAttStruct struct {
	// Index 属性类型
	Index AttributeEnum
	// Value 属性值
	Value int32
}

// Unmarshal Unmarshal
func (r EquipAttStruct) Unmarshal(s []byte) error {
	err := json.Unmarshal(s, &r)
	if err != nil {
		log.Println("error:", err)
	}
	return err
}
