// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

import (
	"encoding/json"
	"log"
)

// ItemStruct 道具表
type ItemStruct struct {
	// ID ID
	ID uint32
	// Name 名称
	Name string
	// Type 类型
	Type ItemTypeEnum
	// Price 价格
	Price float32
	// Stack 最大堆叠数
	Stack uint16
	// Test1 Test1
	Test1 []bool
	// Test2 Test2
	Test2 []int32
	// Test3 Test3
	Test3 bool
	// Test4 Test4
	Test4 []string
	// Test5 Test5
	Test5 EquipAttStruct
	// Icon ICON
	Icon uint32
	// Desc 描述
	Desc string
}

// ItemTable 道具表
var ItemTable = make(map[uint32]*ItemStruct)

// Unmarshal Unmarshal
func (r ItemStruct) Unmarshal(s []byte) error {
	err := json.Unmarshal(s, &r)
	if err != nil {
		log.Println("error:", err)
	}
	return err
}

// ItemTableLoad 数据加载
func ItemTableLoad(s []byte) {
	var data []*ItemStruct
	err := json.Unmarshal(s, &data)
	if err != nil {
		log.Println("error:", err)
		return
	}
	for _, row := range data {
		_, ok := ItemTable[row.ID]
		if ok {
			log.Println("ItemTable replace:", row)
		}
		ItemTable[row.ID] = row
	}
}

// ItemTableRelate 父子表关联
func ItemTableRelate() {
}
