// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

// ItemTypeEnum 道具类型
type ItemTypeEnum int

const (
	// ItemTypeResource 资源
	ItemTypeResource ItemTypeEnum = 1
	// ItemTypeGift 礼包
	ItemTypeGift ItemTypeEnum = 2
	// ItemTypeMedicinal 药品
	ItemTypeMedicinal ItemTypeEnum = 3
	// ItemTypeMaterial 资源
	ItemTypeMaterial ItemTypeEnum = 4
	// ItemTypeEquip 装备
	ItemTypeEquip ItemTypeEnum = 5
)