// Code generated by game config export tool. DO NOT EDIT.
package gameconfig

import (
	"encoding/json"
	"log"
)

// QuestStruct 任务表
type QuestStruct struct {
	// ID ID
	ID uint32
	// Name 任务名称
	Name string
	// Reward 奖励道具
	Reward []uint32
}

// QuestTable 任务表
var QuestTable = make(map[uint32]*QuestStruct)

// Unmarshal Unmarshal
func (r QuestStruct) Unmarshal(s []byte) error {
	err := json.Unmarshal(s, &r)
	if err != nil {
		log.Println("error:", err)
	}
	return err
}

// QuestTableLoad 数据加载
func QuestTableLoad(s []byte) {
	var data []*QuestStruct
	err := json.Unmarshal(s, &data)
	if err != nil {
		log.Println("error:", err)
		return
	}
	for _, row := range data {
		_, ok := QuestTable[row.ID]
		if ok {
			log.Println("QuestTable replace:", row)
		}
		QuestTable[row.ID] = row
	}
}

// QuestTableRelate 父子表关联
func QuestTableRelate() {
}
