// Code generated by game config export tool. DO NOT EDIT.
namespace GameConfig
{
	/// <summary>
	/// 道具属性枚举
	/// </summary>
	public enum AttributeEnum
	{
		/// <summary>
		/// 血量
		/// </summary>
		AttributeHP = 1,
		/// <summary>
		/// 魔法值
		/// </summary>
		AttributeMP = 2,
		/// <summary>
		/// 物理攻击
		/// </summary>
		AttributePATK = 3,
		/// <summary>
		/// 魔法攻击
		/// </summary>
		AttributeMATK = 4,
	}
}
