// Code generated by game config export tool. DO NOT EDIT.
namespace GameConfig
{
	/// <summary>
	/// 装备部位枚举
	/// </summary>
	public enum EquipPosEnum
	{
		/// <summary>
		/// 衣服
		/// </summary>
		EquipPosCoat = 1,
		/// <summary>
		/// 武器
		/// </summary>
		EquipPosWeapon = 2,
		/// <summary>
		/// 裤子
		/// </summary>
		EquipPosTrousers = 3,
		/// <summary>
		/// 帽子
		/// </summary>
		EquipPosHat = 4,
		/// <summary>
		/// 手套
		/// </summary>
		EquipPosGloves = 5,
		/// <summary>
		/// 鞋子
		/// </summary>
		EquipPosShoes = 6,
		/// <summary>
		/// 项链
		/// </summary>
		EquipPosNecklace = 7,
		/// <summary>
		/// 腰带
		/// </summary>
		EquipPosBelt = 8,
	}
}
