// Code generated by game config export tool. DO NOT EDIT.
using System.Runtime.Serialization;

namespace GameConfig
{
	/// <summary>
	/// 装备属性结构体
	/// </summary>
	[DataContract]
	public class EquipAttStruct
	{
		/// <summary>
		/// 属性类型
		/// </summary>
		[DataMember]
		public AttributeEnum Index { get; private set; }
		/// <summary>
		/// 属性值
		/// </summary>
		[DataMember]
		public int Value { get; private set; }

		public void Relate()
		{
		}
	}
}
