// Code generated by game config export tool. DO NOT EDIT.
using System.Runtime.Serialization;

namespace GameConfig
{
	/// <summary>
	/// 常规设置
	/// </summary>
	[DataContract]
	public class GeneralSettingsStruct
	{
		/// <summary>
		/// 初始等级
		/// </summary>
		[DataMember]
		public uint InitLevel { get; private set; }
		/// <summary>
		/// 初始金币
		/// </summary>
		[DataMember]
		public uint InitCoin { get; private set; }
		/// <summary>
		/// 初始道具
		/// </summary>
		[DataMember]
		public uint[] InitItem { get; private set; }
		/// <summary>
		/// InitItem --> Item
		/// </summary>
		public ItemStruct[] InitItem2Item { get; private set; }
		/// <summary>
		/// 初始任务
		/// </summary>
		[DataMember]
		public uint InitQuest { get; private set; }
		/// <summary>
		/// InitQuest --> Quest
		/// </summary>
		public QuestStruct InitQuest2Quest { get; private set; }
		/// <summary>
		/// 世界名称
		/// </summary>
		[DataMember]
		public string WorldName { get; private set; }
		/// <summary>
		/// 是否是新区
		/// </summary>
		[DataMember]
		public bool IsNewWorld { get; private set; }
		/// <summary>
		/// Test1
		/// </summary>
		[DataMember]
		public ItemTypeEnum Test1 { get; private set; }
		/// <summary>
		/// Test2
		/// </summary>
		[DataMember]
		public EquipAttStruct Test2 { get; private set; }
		/// <summary>
		/// Test3
		/// </summary>
		[DataMember]
		public EquipAttStruct[] Test3 { get; private set; }
		/// <summary>
		/// Test5
		/// </summary>
		[DataMember]
		public string[] Test5 { get; private set; }

		public void Relate()
		{
			InitItem2Item = new ItemStruct[InitItem.Length];
			for (int i = 0; i < InitItem.Length; ++i)
			{
				InitItem2Item[i] = TableFacade.ItemTable[InitItem[i]];
			}
			InitQuest2Quest = TableFacade.QuestTable[InitQuest];
		}
	}

	public partial class TableFacade
	{
		public static GeneralSettingsStruct GeneralSettings;
	}
}
