// Code generated by game config export tool. DO NOT EDIT.
namespace GameConfig
{
	/// <summary>
	/// 道具类型
	/// </summary>
	public enum ItemTypeEnum
	{
		/// <summary>
		/// 资源
		/// </summary>
		ItemTypeResource = 1,
		/// <summary>
		/// 礼包
		/// </summary>
		ItemTypeGift = 2,
		/// <summary>
		/// 药品
		/// </summary>
		ItemTypeMedicinal = 3,
		/// <summary>
		/// 资源
		/// </summary>
		ItemTypeMaterial = 4,
		/// <summary>
		/// 装备
		/// </summary>
		ItemTypeEquip = 5,
	}
}
