// Code generated by game config export tool. DO NOT EDIT.
using System.Runtime.Serialization;

namespace GameConfig
{
	/// <summary>
	/// 道具表
	/// </summary>
	[DataContract]
	public class ItemStruct : IConfigStruct<uint>
	{
		/// <summary>
		/// ID
		/// </summary>
		[DataMember]
		public uint ID { get; private set; }
		/// <summary>
		/// 名称
		/// </summary>
		[DataMember]
		public string Name { get; private set; }
		/// <summary>
		/// 类型
		/// </summary>
		[DataMember]
		public ItemTypeEnum Type { get; private set; }
		/// <summary>
		/// 价格
		/// </summary>
		[DataMember]
		public float Price { get; private set; }
		/// <summary>
		/// 最大堆叠数
		/// </summary>
		[DataMember]
		public ushort Stack { get; private set; }
		/// <summary>
		/// Test1
		/// </summary>
		[DataMember]
		public bool[] Test1 { get; private set; }
		/// <summary>
		/// Test2
		/// </summary>
		[DataMember]
		public int[] Test2 { get; private set; }
		/// <summary>
		/// Test3
		/// </summary>
		[DataMember]
		public bool Test3 { get; private set; }
		/// <summary>
		/// Test4
		/// </summary>
		[DataMember]
		public string[] Test4 { get; private set; }
		/// <summary>
		/// Test5
		/// </summary>
		[DataMember]
		public EquipAttStruct Test5 { get; private set; }
		/// <summary>
		/// ICON
		/// </summary>
		[DataMember]
		public uint Icon { get; private set; }
		/// <summary>
		/// 描述
		/// </summary>
		[DataMember]
		public string Desc { get; private set; }

		public void Relate()
		{
		}

		public uint GetKey()
		{
			 return ID;
		}
	}

	public partial class Facade
	{
		public static DataTable<uint, ItemStruct> ItemTable = DataTable<uint, ItemStruct>.Instance;
	}
}
