// Code generated by game config export tool. DO NOT EDIT.
using System.Runtime.Serialization;

namespace GameConfig
{
	/// <summary>
	/// 任务表
	/// </summary>
	[DataContract]
	public class QuestStruct : IConfigStruct<uint>
	{
		/// <summary>
		/// ID
		/// </summary>
		[DataMember]
		public uint ID { get; private set; }
		/// <summary>
		/// 任务名称
		/// </summary>
		[DataMember]
		public string Name { get; private set; }
		/// <summary>
		/// 奖励道具
		/// </summary>
		[DataMember]
		public uint[] Reward { get; private set; }

		public void Relate()
		{
		}

		public uint GetKey()
		{
			 return ID;
		}
	}

	public partial class TableFacade
	{
		public static DataTable<uint, QuestStruct> QuestTable = DataTable<uint, QuestStruct>.Instance;
	}
}
